#===================Config for ChatRegex===================#
#-------------------Format for new entry-------------------#
#   <Entry Name>:
#         world: '<World Name>'
#         x: <X Coords>
#         y: <Y Coords>
#         z: <Z Coords>
#         radius: <Radius>
#         regex: '<The Regular Expression>'
#         action: 0-Do nothing, 1-Cancel the message, 2-Only show message to the player
#         global: Is this a global regex
#         commands: #Use the placeholder %player for player's name and %message for the message.
#         - '<command #1>'
#         - '<command #2>'

regexs:
    test:
        world: 'world'
        x: 0
        y: 0
        z: 0
        radius: 5
        regex: '.*'
        action: 0
        global: false
        commands:
        - 'say Yes %player?'
    global:
        regex: 'Hello|Hi|Hola'
        action: 0
        global: true
        commands:
        - 'say Hello %player!'