#===================Config for ChatRegex===================#
#-------------------Format for new entry-------------------#
#   <Entry Name>:
#         world: '<World Name>'
#         x: <X Coords>
#         y: <Y Coords>
#         z: <Z Coords>
#         radius: <Radius>
#         regex: '<The Regular Expression>'
#         action: 0-Do nothing, 1-Cancel the message, 2-Only show message to the player (Default value is 0)
#         global: Is this a global regex (Default value is true)
#         cooldown: <Cooldown time is seconds> (Default value is 0)
#         global cooldown: Is the cooldown a global cooldown? #If the value is false it will be a per-player cooldown. (Default value is true)
#         commands: #You may use placeholders. #If the delay(d) is not specified it will default to 0 seconds.
#         - c="<command #1>" d=<delay in seconds>
#         - c="<command #2>"
#-----------------------Placeholders-----------------------#
# %player - Player's name.
# %message - Message sent.
# %cg# - Capture group #.
#

regexs:
    test:
        world: 'world'
        x: 0
        y: 0
        z: 0
        radius: 5
        regex: '.*'
        action: 0
        global: false
        commands:
        - c="say Yes %player?"
    global:
        regex: 'Hello|Hi|Hola'
        action: 0
        global: true
        cooldown: 5
        global cooldown: true
        commands:
        - c="say Hello %player!" d=9