name: ChatRegex
main: me.alexlander123.chatregex.ChatRegex
version: 1.5
author: AlexLander123
description: >
             ChatRegex!
commands:
   chatregexreload:
     description: Reload ChatRegex Config.
     aliases: [crreload]
     permission: chatregex.reload
permissions:
   chatregex.reload:
     description: Access to chatregexreload.